service: clean-serverless-api

frameworkVersion: '3'

useDotenv: true
configValidationMode: warn

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
  - serverless-plugin-lambda-insights
  - serverless-prune-plugin
  - serverless-plugin-optimize
  - serverless-plugin-conditional-functions
  - serverless-domain-manager
  - serverless-api-gateway-caching
  - serverless-offline #needs to be last in the list

provider:
  name: aws
  runtime: nodejs18.x

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - src/**
    - '!.github/**'
    - '!.scafflater/**'
    - '!.scannerwork/**'
    - '!.vscode/**'
    - '!coverage/**'
    - '!dist-*/**'
    - '!dist/**'
    - '!kube/**'
    - '!resources/**'
    - '!test/**'
    - '!.editorconfig'
    - '!.eslintrc.json'
    - '!.gitignore'
    - '!.nvmrc'
    - '!.prettier*'
    - '!catalog-info.yaml'
    - '!jest.config.js'
    - '!package.json'
    - '!package-lock.json'
    - '!Jenkinsfile'
    - '!jenkins.env'
    - '!README.md'
    - '!scripts.sh'
    - '!serverless.yml'
    - '!sonar-project.properties'

custom:
  apiGatewayCaching:
    enabled: true

functions:
  getUsers:
    enabled: true
    handler: src/main/routes/get-user-route.getUserHandler
    timeout: 900
    events:
      - http:
          path: /user/{name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                name: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.name
