name: Build
on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'release/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - .github/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - .github/**
  workflow_dispatch:
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: Test and coverage
        run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
